<?php

namespace Tests\Feature;

use App\Models\Post;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DeletePostTest extends TestCase
{
    use RefreshDatabase;

    protected $endpoint = 'api/post';

    protected $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = $this->createUser();
    }


    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_delete_endpoint()
    {
        $response = $this->delete( $this->endpoint );

        $response->assertForbidden();
    }

    public function test_user_not_post_owner()
    {
        $user = User::factory()->create();
        $postData = Post::factory()->raw();
        $post = $user->posts()->create( $postData );
        $postID = $post->id;

        $response = $this
            ->actingAs($this->user)
            ->delete( $this->endpoint."/$postID" );

        $response->assertForbidden();
    }

    public function test_post_not_found()
    {
        $fakePostID = 9999;
        $response = $this
            ->actingAs($this->user)
            ->delete( $this->endpoint."/$fakePostID" );

        $response->assertNotFound();
    }

    public function test_post_delete_successfully()
    {
        $postData = Post::factory()->raw();
        $post = $this->user->posts()->create($postData);
        $postID = $post->id;
        $response = $this
            ->actingAs($this->user)
            ->delete( $this->endpoint."/$postID" );

        $response->assertOk();
    }
}
