<?php

use App\Models\Post;
use Tests\TestCase;

class GetPostsTest extends TestCase
{
    protected $endpoint = 'api/posts';

    protected $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = $this->createUser();
    }



    public function test_posts_endpoint()
    {
        $this->get($this->endpoint)
            ->assertStatus(self::HTTP_OK );
    }

    public function test_it_returns_a_success_response_with_post_data()
    {
        Post::factory()->count(5)->create();


        // When
        $response = $this->get($this->endpoint);

        // Then
        $response->assertStatus(self::HTTP_OK)
            ->assertJson([
                'success' => true,
                'message' => 'Posts gotten',
            ]);
    }
}
