<?php

namespace Tests\Feature;

use App\Models\User;
use Tests\TestCase;

class ProfileTest extends TestCase
{
    protected $endpoint = 'api/account/profile';

    protected $user;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = $this->createUser();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_profile_update_endpoint()
    {
        $response = $this->post($this->endpoint);
        $response->assertStatus(self::HTTP_REDIRECT );
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_get_profile_endpoint()
    {
        $response = $this->get($this->endpoint);
        $response->assertStatus(self::HTTP_REDIRECT );
    }

    public function test_profile_update_success()
    {
        $userData = User::factory()->raw();

        $response = $this
            ->actingAs($this->user)
            ->post($this->endpoint, $userData);
        $response->assertStatus(self::HTTP_CREATED );
    }

    public function test_get_profile_success()
    {
        $userData = User::factory()->raw();

        $response = $this
            ->actingAs($this->user)
            ->get($this->endpoint, $userData);
        $response->assertStatus(self::HTTP_OK )
            ->assertJsonStructure(['token']);
    }
}
